baseURL = "http://localhost"
languageCode = "es-ES"
title = "Sambo Granollers"
buildFuture = true

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

[Taxonomies]
    tag = "tags"

[imaging]
    resampleFilter = "box"
    quality = 75
    anchor = "Center"

#----------------
# MENU PRINCIPAL
#----------------

[[menu.main]]
	Name = "Inicio"
    Weight = 1
    Identifier = "home"
    URL = "/"

[[menu.main]]
	Name = "Noticias"
    Weight = 3
    Identifier = "noticias"
    URL = "/noticias"

[[menu.main]]
	Name = "Galería"
    Weight = 5
    Identifier = "galeria"
    URL = "/galeria"

[[menu.main]]
	Name = "Agenda"
    Weight = 7
    Identifier = "agenda"
    URL = "/agenda"

[[menu.main]]
	Name = "Quiénes somos"
    Weight = 9
    Identifier = "who"
    URL = "/who"

[[menu.main]]
	Name = "Contacto"
    Weight = 11
    Identifier = "contact"
    URL = "#contact"
