backend:
  branch: master
  name: git-gateway
  #name: github
  #repo: davidayalas/new-ckm

display_url: https://www.sambogranollers.com

media_folder: "/content/media" # Media files will be stored in the repo under static/images/uploads
public_folder: "/media"
#publish_mode: editorial_workflow

collections: # A list of collections the CMS should be able to edit
  - name: "general"
    label: "General"
    folder: "content"
    create: false
    delete: false
    editor: 
      preview: false     
    slug: "{{slug}}"
    filter: {field: "kind", value: "general"}
    fields:
      - {label: "Título", name: "title", widget: "string", required: true}
      - {label: "Título 2", name: "title2", widget: "string", required: true}
      - {label: "Horarios", name: "schedule", widget: "string", required: true}
      - {label: "Dirección", name: "address", widget: "string", required: true}
      - {label: "Teléfono", name: "phone", widget: "string", required: true}
      - {label: "Email", name: "email", widget: "string", required: true}
      - name: social
        label: Contact
        widget: list
        fields:
          - {label: "Título", name: "title", widget: string}
          - {label: "Enlace", name: "link", widget: string}
          - {label: "CSS Class", name: "class", widget: string}
      - {label: "Paginación", name: "pagination", widget: "number", required: true, default: 5}

  - name: "galeria"
    label: "Galeria"
    folder: "content/galeria"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor: 
      preview: false     
    fields:
      - {label: "Título", name: "title", widget: string}
      - {label: "Fecha", name: "date", widget: date}
      - {label: "Imagen", name: "image", widget: image, required: false}
      - {label: "Youtube", name: "youtube", widget: string, required: false}

  - name: "noticias"
    label: "Noticias"
    folder: "content/noticias"
    sort: "date:desc"
    create: true
    slug: "{{slug}}"
    editor: 
      preview: false     
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Descripción", name: "description", widget: "string"}
      - {label: "Fecha", name: "date", widget: "datetime"}
      - {label: "Contenido", name: "body", widget: "markdown"}
      - name: images
        label: Imágenes
        widget: list
        fields:
          - {label: "Descripción", name: "title", widget: string}
          - {label: "Imagen", name: "image", widget: image, required: false}
          - {label: "Youtube", name: "youtube", widget: string, required: false}

  - name: "agenda"
    label: "Agenda"
    folder: "content/agenda"
    create: true
    slug: "{{slug}}-{{year}}-{{month}}-{{day}}"
    editor: 
      preview: false     
    sort: "date:desc"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Descripción", name: "description", widget: "string", required: false}
      - {label: "Fecha", name: "date", widget: "datetime"}
      - {label: "Hora", name: "hora", widget: "string"}
      - {label: "Lugar", name: "lloc", widget: "string"}
      - {label: "Contenido", name: "body", widget: "markdown"}

  - name: "others"
    label: "Otros"
    folder: "content"
    sort: "date:desc"
    create: false
    delete: false
    slug: "{{slug}}"
    editor: 
      preview: false     
    filter: {field: "kind", value: "orphan"}
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Descripción", name: "description", widget: "string"}
      - {label: "Contenido", name: "body", widget: "markdown"}
